### ISSUE TITLE
Evaluate Ruby code - Not Working after following Steps (RVM)

### ISSUE THREAD

**Issue by dregules** [JoshCheek/sublime-text-2-and-3-seeing-is-believing#15]
Hi @JoshCheek  - first of all: thank you for sharing this awesome plugin. I'm just learning to code, and I believe this would make a huge difference in the process..
  
Second, I need your help, because I can't find anything else online that guides me through troubleshooting..

I followed every step, as you see in the screenshots below: 
<img width="1280" alt="screen shot 2015-07-09 at 22 52 14" src="https://cloud.githubusercontent.com/assets/1048262/8607819/af190902-268d-11e5-92bd-6ecaf13f1f10.png">

<img width="561" alt="screen shot 2015-07-09 at 22 54 06" src="https://cloud.githubusercontent.com/assets/1048262/8607820/af19782e-268d-11e5-86e7-e18bf13b9c2b.png">

Yet , I certainly do not see the evaluation results after selecting it..

![image](https://cloud.githubusercontent.com/assets/1048262/8607869/f269985c-268d-11e5-8f44-2827dbb4c6bb.png)

I honestly don't know what it may be that I missed. Any insight will be greatly appreciated!
Thank you very much in advance - Keep on rocking, your Ruby Kickstart is teaching me how to code.

**Comment by dregules** [comment]
Uninstalled and the reinstalled and added RVM to Bash profile and then followed steps from a colleague's blog post:
http://www.roidriscoll.co.uk/gems/articles/tutorials/2014/06/21/seeing-is-believing/#

**Comment by JoshCheek** [comment]
Hey, just saw this. So you got it working? I need to make the errors pop up on Sublime :/ Right now you have to open the console to see them (Control+`), and even then, they're not very helpful. If you didn't get it working, let me know, we'll figure it out (if I don't respond for a day, ping me on Twitter @josh_cheek, I get overwhelmed by email and stop checking it).

**Comment by dregules** [comment]
Yes I did Josh, you can't imagine how helpful this is - thanks for your response! I understand. 
What I couldn't get working are the shortcut keys inside Sublime Txt 3, to run Seeing Is Believing Evaluate function / eliminate annotations. Basically when hitting `⌥ + ⌘ + B` brings up at the bottom No Build System or `⌥ + ⌘ + V` just pastes whatever is on Clipboard. 

I mean it's all good with hitting ⌥ + ⌘ + P and then selecting Evaluate from the menu, but I was curious if there's some insight in how to get the shortcut keys sorted out.

**Comment by JoshCheek** [comment]
That is strange. They get selected based on the keymap in this file: https://github.com/JoshCheek/sublime-text-2-and-3-seeing-is-believing/blob/master/Default%20(OSX).sublime-keymap

Notice that the selector is `source.ruby`, so the keybindings are only applied when Sublime considers the code to be Ruby. You may need to explicitly set it to Ruby.

If not that, then check that the keybindings file doesn't have local changes -- if you cloned the repo with git, you can run `git diff 'Default (OSX).sublime-keymap'`. Also, make sure it's valid (not sure how to do that, probably see if node.js will evaluate it `node 'Default (OSX).sublime-keymap'`, assuming you have node) if the file were invalid, that could cause Sublime to stop evaluating it and not get the keybindings set.

**Comment by dregules** [comment]
what's strange is that I was interpreting `⌥` as SHIFT. What a fucking waste of neurons into this, I feel so stupid about it, SORRY for carrying you on board too. 
THANK YOU for all your support and definitely keep up the awesome work - YOU ROCK!

**Comment by JoshCheek** [comment]
lol, np, these things happen :)
