### ISSUE TITLE
Can I speak to Peter Pan please? 

### ISSUE THREAD

**Issue by prstockton** [JoshCheek/sublime-text-2-and-3-seeing-is-believing#19]
Successfully installed on Sublime Text but if I Cmd-Z (I get that I should be using SIB Remove annotations, but you know...).

Anyway, I get a line from Barrie.....

Am I just a cultural philistine or is that odd?

 "you_know_that_place_between_sleep_and_awake_that_place_where_you_still_remember_dreaming_thats_where_ill_always_love_you"

**Comment by JoshCheek** [comment]
I amused myself while writing this by naming things quotes from Hook (IIRC), in this case, it comes from https://github.com/JoshCheek/sublime-text-2-and-3-seeing-is-believing/blob/c8e303964c5255f535be317aa5b3ad7b3a15dc8d/seeing_is_believing.py#L62

So, the naming isn't what's unexpected, but the fact that you see the name is. Eg when I press Cmd-Z (a totally viable strategy depending on your workflow), it simply reverts that one change.

![sublime-sib](https://cloud.githubusercontent.com/assets/77495/23962263/8429f68e-097b-11e7-8a9d-76cc4865475b.gif)

One thing you might try is Control-backtick, which will open the Sublime console, if there's an error it might have more information there.

**Comment by JoshCheek** [comment]
I'm going to close this, but go ahead and reopen it if you still have the issue and you want me to try troubleshooting it with you.
