### ISSUE TITLE
Doesn't seem to work in sublime text 2

### ISSUE THREAD

**Issue by bertomartin** [JoshCheek/sublime-text-2-and-3-seeing-is-believing#7]
When I try to evaluate the marked lines, it just deletes them instead.

**Comment by JoshCheek** [comment]
Uhm, I'm way late to this (sorry @rongierlach, I'm on a lot of organizations in GH, so I get a ton of spam from GH, and have a tendency to miss the relevant ones)

Best thing I learned for working with Sublime is that Control+` (backtick) opens a dev console where you can see error messages and so forth, which are a much better source of feedback than your file just going blank.

You're probably way past this now, but what does it say when you do `/path/to/your/wrapper/ruby seeing_is_believing -v`?
